### ISSUE TITLE
Cybro Repository not found in HACS

### ISSUE THREAD

**Issue by dragansaldziev** [killer0071234/ha-cybro#7]
I am unable to find the Cybro repository in HACS, is it still up? I am using Cybro HiQ by Robotina in my home and would love to try and integrate it with HA.
![Capture](https://user-images.githubusercontent.com/109673057/183284718-eefe862d-d681-4668-b566-f5b5d7aed583.PNG)

**Comment by killer0071234** [comment]
> I am unable to find the Cybro repository in HACS, is it still up? I am using Cybro HiQ by Robotina in my home and would love to try and integrate it with HA. ![Capture](https://user-images.githubusercontent.com/109673057/183284718-eefe862d-d681-4668-b566-f5b5d7aed583.PNG)

Hi,
currently its not yet in the HACS store.
Currently its slowly growing and at the moment there are only LC-10-IQ, power meter and temperature sensors supported.
If you want to try it out, you can manually add the repository on the right top corner (menu -> add user defined repository) and enter `https://github.com/killer0071234/ha-cybro` as repository with category `integration`.
But for communicating with the Cybro HIQ plc you need the cybro scgi server running. You can run the scgi server as docker container, see: `https://hub.docker.com/r/killer007/cybroscgiserver`
BR Daniel

**Comment by dragansaldziev** [comment]
Hi Daniel, thank you for your reply and your continued effort. I will follow the development since right now i could only connect the LC since I don’t have a power meter and the temperature sensors I am using are Netatmo and already have an existing HA integration. It would be amazing if you would do a blinds controller integration, I have interesting use cases for that. Thank you and have a great start to the week!

**Comment by killer0071234** [comment]
Hi,
the first release with blind support is online!
but you need to add the new repo also by hand to test it.

`https://github.com/killer0071234/ha-hiq`

this repository is soon obsolete

**Comment by killer0071234** [comment]
Hi,
The new  HIQ integration is now directly available in the HACS store under integrations!
I will close this issue.
BR Daniel
